image: node:8.11.2

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm install hexo-cli -g
    - npm install
    - hexo clean
    - hexo generate
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master